# Generated by Django 6.0.3 on 2026-04-06 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.TextField(blank=True, verbose_name="头像"),
        ),
    ]
