# Generated by Django 6.0.3 on 2026-04-06 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_alter_user_avatar"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="notify_email",
            field=models.BooleanField(default=True, verbose_name="邮件提醒"),
        ),
        migrations.AddField(
            model_name="user",
            name="notify_sms",
            field=models.BooleanField(default=False, verbose_name="短信提醒"),
        ),
        migrations.AddField(
            model_name="user",
            name="profile_delivery_tag",
            field=models.CharField(blank=True, max_length=20, verbose_name="投递标签"),
        ),
        migrations.AddField(
            model_name="user",
            name="profile_office",
            field=models.CharField(blank=True, max_length=40, verbose_name="办公地点"),
        ),
        migrations.AddField(
            model_name="user",
            name="profile_skills",
            field=models.CharField(blank=True, max_length=80, verbose_name="擅长标签"),
        ),
        migrations.AddField(
            model_name="user",
            name="profile_team",
            field=models.CharField(blank=True, max_length=40, verbose_name="所属团队"),
        ),
        migrations.AddField(
            model_name="user",
            name="profile_title",
            field=models.CharField(blank=True, max_length=40, verbose_name="职位/头衔"),
        ),
        migrations.AddField(
            model_name="user",
            name="remember_device",
            field=models.BooleanField(default=True, verbose_name="记住设备"),
        ),
    ]
