# Generated by Django 6.0.3 on 2026-04-01 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "comp_compId",
                    models.CharField(
                        db_index=True, max_length=64, unique=True, verbose_name="公司ID"
                    ),
                ),
                (
                    "comp_compIndustry",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="公司行业"
                    ),
                ),
                (
                    "comp_compLogo",
                    models.URLField(
                        blank=True, max_length=500, verbose_name="公司Logo"
                    ),
                ),
                (
                    "comp_compName",
                    models.CharField(
                        db_index=True, max_length=255, verbose_name="公司名称"
                    ),
                ),
                (
                    "comp_compScale",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="公司规模"
                    ),
                ),
                (
                    "comp_compStage",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="融资阶段"
                    ),
                ),
                (
                    "comp_link",
                    models.URLField(
                        blank=True, max_length=500, verbose_name="公司链接"
                    ),
                ),
            ],
            options={
                "verbose_name": "公司",
                "verbose_name_plural": "公司",
                "db_table": "job_company",
                "indexes": [
                    models.Index(fields=["comp_compName"], name="idx_company_name"),
                    models.Index(
                        fields=["comp_compIndustry"], name="idx_company_industry"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Recruiter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "recruiter_recruiterId",
                    models.CharField(
                        db_index=True,
                        max_length=64,
                        unique=True,
                        verbose_name="招聘者ID",
                    ),
                ),
                (
                    "recruiter_chatted",
                    models.BooleanField(default=False, verbose_name="是否已沟通"),
                ),
                (
                    "recruiter_imId",
                    models.CharField(
                        blank=True, db_index=True, max_length=64, verbose_name="IM ID"
                    ),
                ),
                (
                    "recruiter_imShowText",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="IM展示文案"
                    ),
                ),
                (
                    "recruiter_imStatus",
                    models.IntegerField(blank=True, null=True, verbose_name="IM状态"),
                ),
                (
                    "recruiter_imUserType",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="IM用户类型"
                    ),
                ),
                (
                    "recruiter_inDay",
                    models.IntegerField(blank=True, null=True, verbose_name="活跃天数"),
                ),
                (
                    "recruiter_recruiterName",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="招聘者姓名"
                    ),
                ),
                (
                    "recruiter_recruiterPhoto",
                    models.URLField(
                        blank=True, max_length=500, verbose_name="招聘者头像"
                    ),
                ),
                (
                    "recruiter_recruiterTitle",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="招聘者职位"
                    ),
                ),
            ],
            options={
                "verbose_name": "招聘者",
                "verbose_name_plural": "招聘者",
                "db_table": "job_recruiter",
                "indexes": [
                    models.Index(
                        fields=["recruiter_recruiterName"], name="idx_recruiter_name"
                    ),
                    models.Index(fields=["recruiter_imId"], name="idx_recruiter_imid"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "dataInfo",
                    models.JSONField(
                        blank=True, null=True, verbose_name="原始dataInfo"
                    ),
                ),
                (
                    "dataParams",
                    models.JSONField(
                        blank=True, null=True, verbose_name="原始dataParams"
                    ),
                ),
                (
                    "job_advViewFlag",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="广告展示标识"
                    ),
                ),
                (
                    "job_campusJobKind",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="校招类型"
                    ),
                ),
                (
                    "job_dataPromId",
                    models.CharField(blank=True, max_length=100, verbose_name="推广ID"),
                ),
                (
                    "job_dq",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=100,
                        verbose_name="工作地点",
                    ),
                ),
                (
                    "job_g",
                    models.CharField(blank=True, max_length=255, verbose_name="job_g"),
                ),
                (
                    "job_h5OuterLink",
                    models.URLField(blank=True, max_length=500, verbose_name="H5外链"),
                ),
                ("job_j", models.TextField(blank=True, verbose_name="岗位描述")),
                (
                    "job_jobId",
                    models.CharField(
                        db_index=True, max_length=64, unique=True, verbose_name="岗位ID"
                    ),
                ),
                (
                    "job_jobKind",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="岗位类型"
                    ),
                ),
                ("job_labels", models.TextField(blank=True, verbose_name="岗位标签")),
                (
                    "job_link",
                    models.URLField(
                        blank=True, max_length=500, verbose_name="岗位链接"
                    ),
                ),
                (
                    "job_pcOuterLink",
                    models.URLField(blank=True, max_length=500, verbose_name="PC外链"),
                ),
                (
                    "job_refreshTime",
                    models.DateTimeField(
                        blank=True, db_index=True, null=True, verbose_name="刷新时间"
                    ),
                ),
                (
                    "job_requireEduLevel",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="学历要求"
                    ),
                ),
                (
                    "job_requireWorkYears",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="工作年限"
                    ),
                ),
                (
                    "job_salary",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=100,
                        verbose_name="薪资文本",
                    ),
                ),
                (
                    "salary_min",
                    models.IntegerField(
                        blank=True, db_index=True, null=True, verbose_name="最低薪资(K)"
                    ),
                ),
                (
                    "salary_max",
                    models.IntegerField(
                        blank=True, db_index=True, null=True, verbose_name="最高薪资(K)"
                    ),
                ),
                (
                    "job_title",
                    models.CharField(
                        db_index=True, max_length=255, verbose_name="岗位标题"
                    ),
                ),
                (
                    "job_topJob",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="是否置顶"
                    ),
                ),
                (
                    "query_city_code",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=32,
                        verbose_name="城市编码",
                    ),
                ),
                (
                    "query_city_dq_code",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=32,
                        verbose_name="城市地区编码",
                    ),
                ),
                (
                    "query_city_name",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=100,
                        verbose_name="城市名称",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="jobs",
                        to="job.company",
                        verbose_name="公司",
                    ),
                ),
                (
                    "recruiter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="jobs",
                        to="job.recruiter",
                        verbose_name="招聘者",
                    ),
                ),
            ],
            options={
                "verbose_name": "岗位",
                "verbose_name_plural": "岗位",
                "db_table": "job_job",
                "indexes": [
                    models.Index(fields=["job_title"], name="idx_job_title"),
                    models.Index(fields=["query_city_name"], name="idx_job_city_name"),
                    models.Index(fields=["query_city_code"], name="idx_job_city_code"),
                    models.Index(
                        fields=["salary_min", "salary_max"], name="idx_job_salary_range"
                    ),
                    models.Index(
                        fields=["job_refreshTime"], name="idx_job_refresh_time"
                    ),
                    models.Index(fields=["job_topJob"], name="idx_job_top"),
                ],
            },
        ),
    ]
